name: apiverve_ipdemographics
description: IP Demographics combines IP geolocation with Census demographic data to provide demographic information for any IP address. Get location, income, education, and housing data based on the IP's geographic location.
version: 1.1.14
homepage: https://apiverve.com/marketplace/ipdemographics?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/ipdemographics-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
