// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.IPDemographics
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("ip")]
        public string Ip { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("demographics")]
        public Demographics Demographics { get; set; }

        [JsonProperty("acsYear")]
        public long AcsYear { get; set; }
    }

    public partial class Demographics
    {
        [JsonProperty("population")]
        public long Population { get; set; }

        [JsonProperty("medianAge")]
        public double MedianAge { get; set; }

        [JsonProperty("medianHouseholdIncome")]
        public long MedianHouseholdIncome { get; set; }

        [JsonProperty("perCapitaIncome")]
        public long PerCapitaIncome { get; set; }

        [JsonProperty("medianHomeValue")]
        public long MedianHomeValue { get; set; }

        [JsonProperty("collegeEducatedPct")]
        public double CollegeEducatedPct { get; set; }

        [JsonProperty("unemploymentRate")]
        public double UnemploymentRate { get; set; }

        [JsonProperty("homeOwnershipRate")]
        public double HomeOwnershipRate { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("zip")]
        public long Zip { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("stateCode")]
        public string StateCode { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }
    }
}
